# Generated by Django 5.2.9 on 2025-12-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10),
        ),
    ]
